INSERT INTO pizza (name, description, photo, price) VALUES
('Margherita', 'Pizza classica con pomodoro, mozzarella e basilico', 'margherita.jpg', 5.50),
('Marinara', 'Pizza con pomodoro, aglio, origano e olio', 'marinara.jpg', 4.50),
('Diavola', 'Pizza con pomodoro, mozzarella e salame piccante', 'diavola.jpg', 7.00),
('Quattro Stagioni', 'Pizza con pomodoro, mozzarella, funghi, prosciutto, carciofi e olive', 'quattro_stagioni.jpg', 8.50),
('Capricciosa', 'Pizza con pomodoro, mozzarella, prosciutto cotto, funghi e carciofi', 'capricciosa.jpg', 8.00),
('Bufalina', 'Pizza con mozzarella di bufala, pomodoro e basilico fresco', 'bufalina.jpg', 9.00),
('Prosciutto e Funghi', 'Pizza con pomodoro, mozzarella, prosciutto cotto e funghi', 'prosciutto_funghi.jpg', 7.50),
('Quattro Formaggi', 'Pizza con mozzarella, gorgonzola, fontina e parmigiano', 'quattro_formaggi.jpg', 8.00),
('Ortolana', 'Pizza vegetariana con zucchine, melanzane e peperoni', 'ortolana.jpg', 7.00),
('Tonno e Cipolla', 'Pizza con pomodoro, mozzarella, tonno e cipolla', 'tonno_cipolla.jpg', 7.50),
('Napoli', 'Pizza con pomodoro, mozzarella, acciughe e capperi', 'napoli.jpg', 6.50),
('Boscaiola', 'Pizza con mozzarella, salsiccia e funghi porcini', 'boscaiola.jpg', 8.50),
('Frutti di Mare', 'Pizza con pomodoro e mix di frutti di mare', 'frutti_mare.jpg', 9.50),
('Calzone', 'Pizza chiusa con ricotta, salame e mozzarella', 'calzone.jpg', 7.50),
('Vegetariana Speciale', 'Pizza con mozzarella e verdure grigliate miste', 'vegetariana_speciale.jpg', 7.80);